apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-applications
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/YOURORG/gitops-platform.git
        revision: main

        directories:
          - path: applications/*

  template:
    metadata:
      name: '{{path.basename}}'

    spec:
      project: platform

      source:
        repoURL: https://github.com/YOURORG/gitops-platform.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true